#ifndef SPACESHIPBP_POSITIONINRECTANGLE_H
#define SPACESHIPBP_POSITIONINRECTANGLE_H

#include <enum.h>

BETTER_ENUM(
    PositionInRectagle, int,
    UPPER_LEFT  , UPPER_CENTER   , UPPER_RIGHT  ,
    CENTER_LEFT , CENTER         , CENTER_RIGHT ,
    BOTTOM_LEFT , BOTTOM         , BOTTOM_RIGHT  )

#endif //SPACESHIPBP_POSITIONINRECTANGLE_H
